apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  sources:
    - chart: istiod
      repoURL: "https://istio-release.storage.googleapis.com/charts"
      targetRevision: 1.23.3
