apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-service-staging
  namespace: argocd
  labels:
    app: fake-example
    system: kustomize-example
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    path: examples/kustomize/my-service/overlay/staging
    repoURL: https://github.com/dag-andersen/argocd-diff-preview
